### ISSUE TITLE
Adding a page of companies including current job postings

### ISSUE THREAD

**Issue by azharichenko** [PittCSWiki/pittcswiki#10]
Features:
 - Create a ranking system for how safe a company is
 - How much skill do you need for a certain place?

**Comment by varughese** [comment]
should we still do this? i think a more valuable thing for now would be to get interview journeys from people, and in the frontmatter of it store the company name, and then in the future if we want to we can query for company name or somethin

**Comment by varughese** [comment]
can link to the csc  internships listing page
