### ISSUE TITLE
Add 'related guides' component to guides

### ISSUE THREAD

**Issue by rohit-ganguly** [PittCSWiki/pittcswiki#104]
Helpful for navigating pages. These can simply be populated manually.

**Comment by varughese** [comment]
i think the easiest way to do this is to train an RNN on the titles and contents of our articles and spend $1000 ish on hosting a service on google cloud platform that runs it, then call that api in our files. wdyt @Zmwang622

**Comment by varughese** [comment]
jk. i think a good way to do this is in the frontmatter, add related_guides and have it be an array of the slugs of the other courses

the only problem is if we move around and rename things, then it might mess things up

however we can fix that with #123

**Comment by varughese** [comment]
decided not worth. to add code for this, if certain pages have related guides, they can just be added at the bottom like

```
## Related Guides
1.  [jawn](/jawn)
2.  [jawn](/jawn)
3. [jawn](/jawn)
```

**Comment by varughese** [comment]
changed my mind, dont think this is worth closing

**Comment by varughese** [comment]
what would be some examples of guides and their related guides?

**Comment by Zmwang622** [comment]
any guide on majors, minors would be related to the schedluing guide. Zero to Offer guides related to each other etc
