### ISSUE TITLE
table of contents on left side of long articles

### ISSUE THREAD

**Issue by varughese** [PittCSWiki/pittcswiki#107]
for those long ass articles, a table of contents on the left would be nice

like how they have on google docs

shown on screens with > 900px so can just be a fixed position thing

![image](https://user-images.githubusercontent.com/13937711/82780105-1bc30b80-9e24-11ea-9017-e036b8c38433.png)

**Comment by Zmwang622** [comment]
👍 to this. Yangshun does it similarly where he has the contents on the left
