### ISSUE TITLE
Zero to Offer Application process doc

### ISSUE THREAD

**Issue by Zmwang622** [PittCSWiki/pittcswiki#111]
feel like zero to offer should have a separate website that links to wiki pages for marketing purposes

**Comment by varughese** [comment]
maybe? maybe we can keep it on wiki this year and if we have 0 turnout try making its own page

**Comment by Zmwang622** [comment]
I'll make a page in my free time and it'll probably take like 10 months to make because I'm lazy. So sounds good to me.

**Comment by Zmwang622** [comment]
Draft is complete
