### ISSUE TITLE
Computational Biology / CS and Pre Med

### ISSUE THREAD

**Issue by varughese** [PittCSWiki/pittcswiki#125]
Jason walker could help. And so could Bret Barkley

**Comment by Zmwang622** [comment]
and Kenan Rustamov
and Tao sheng

**Comment by varughese** [comment]
wow so many people

**Comment by Zmwang622** [comment]
so many

**Comment by Zmwang622** [comment]
@varughese should we ask jay to write this now

**Comment by varughese** [comment]
jay aint gonna write this bro

**Comment by Zmwang622** [comment]
alright I'll ask tao
