### ISSUE TITLE
Add a kind of applying assistant

### ISSUE THREAD

**Issue by azharichenko** [PittCSWiki/pittcswiki#13]
So this would be take a short survey and then it would give them a list of companies to shoot for.

**Comment by Zmwang622** [comment]
@azharichenko do we still want to do this

**Comment by azharichenko** [comment]
This is for a wiki 2.0, but I think maybe guiding a person towards certain jobs is not a bad ideas. 
So like this could be pick a path for using your CS degree like web dev, backend, etc. etc. and here is a list of companies. Take a look at what they want in an individual and basically turn that into a check list of things to investigate and build up on so that you can boost yourself up as a candidate and really shine.

**Comment by varughese** [comment]
sounds like this idea could be its own company

**Comment by varughese** [comment]
closing because dont think anyone is going to add this
