### ISSUE TITLE
Bug on cross regristration link

### ISSUE THREAD

**Issue by varughese** [PittCSWiki/pittcswiki#135]
this is on the cross registration page:

```
 1. Fill out [this form]([https://www.google.com/search?q=pitt+cross+registration+form](https://www.google.com/search?q=pitt+cross+registration+form)) 

```

thats an invalid markdown link

should add unit test in #123 to pre check for things like this

**Comment by Zmwang622** [comment]
yeah i messed up. you really wanna add unit tests

**Comment by varughese** [comment]
It would just read all markdown files and look for links, make sure they
are proper links. Wouldn't be that much work but make it more maintainable
in the future

**Comment by varughese** [comment]
also guides/ 

skills/hackathon is wrong 

could add unit test for not markdown files, but dont think itts worth it, can just manually check those

**Comment by varughese** [comment]
close by. #151
