### ISSUE TITLE
Add companies reviews to companies page

### ISSUE THREAD

**Issue by azharichenko** [PittCSWiki/pittcswiki#14]

**Comment by varughese** [comment]
should we make the wiki a shitter version of glassdoor? idk, i think having detailed interview and internship journey posts might be more valuable and niche

wdyallthink + @Zmwang622 @rohit-ganguly

**Comment by Zmwang622** [comment]
What's funny is glassdoor is pretty shitty. But I agree company reviews are kinda out of the domain of the wiki

**Comment by Zmwang622** [comment]
Maybe if we reviewed local companies like Dick's, UPMC? Even then major EH

**Comment by Zmwang622** [comment]
@varughese I think we should close this

**Comment by varughese** [comment]
You can do honors
