### ISSUE TITLE
Better intro to guides on /guides/ page

### ISSUE THREAD

**Issue by varughese** [PittCSWiki/pittcswiki#176]
if you are a high schooler start here

if you are a transfer start here

if you are looking for jobs go here

something like that so its easier for whoever comes in to get the right content

**Comment by varughese** [comment]
also pages like "academics" or "career" could be a little nicer if they had blocks instead of links

**Comment by Zmwang622** [comment]
IS this closed now?

**Comment by varughese** [comment]
No
