### ISSUE TITLE
Zero to Offer

### ISSUE THREAD

**Issue by varughese** [PittCSWiki/pittcswiki#178]
https://drive.google.com/drive/folders/1FNi88dix0gZyZLjS35KjVomy6OGErHjo

Best collection of guides ever

- [x] Move resume to /career/resume , redirect /zero-to-offer/resume to there

- [x] Index @varughese 
   - [x] Writing
   - [x] Feedback

- [x] Application Process Overview @Zmwang622 
   - [x] Writing
   - [x] Feedback
- [x] Mindset @varughese 
   - [x] Writing
   - [x] Feedback

- [x] Building your Case @varughese 
   - [x] Writing
   - [x] Feedback

- [x] Acing your Interview @Zmwang622 
   - [x] Writing
   - [x] Feedback

- [x] Post Interview @Zmwang622 
   - [x] Writing
   - [x] Feedback

- [x] Potpurri 

All writing will be in the google drive and commenting, and then after reviewing in there will get a big PR merged in to finish it https://drive.google.com/drive/folders/1FNi88dix0gZyZLjS35KjVomy6OGErHjo

DUE July 15th

**Comment by Zmwang622** [comment]
this looks sm better than the google doc lmao
