### ISSUE TITLE
How to LeetCode Effectively Guide

### ISSUE THREAD

**Issue by Zmwang622** [PittCSWiki/pittcswiki#179]
co-write this jawn

**Comment by varughese** [comment]
should be in sample study plans?

**Comment by rohit-ganguly** [comment]
i can cowrite an introduction to getting started w interview prep

**Comment by Zmwang622** [comment]
nah its all good @rohit-ganguly this guide is getting covered elsewhere

**Comment by varughese** [comment]
part of zero to offer #178

**Comment by Zmwang622** [comment]
cool cool nice nice
