### ISSUE TITLE
Better/more Search Tags

### ISSUE THREAD

**Issue by Zmwang622** [PittCSWiki/pittcswiki#186]
A lot of the giudes don't have enough search tags so I'll go through and add them. Here's a list of the ones I found that need more tags feel free to lmk others that need more tags:

- HS Guide
- Career Fair Guide
- ALl the zero to offer guides
- Stat minor guide
- 1699 guide
- team matching + personal website.

**Comment by varughese** [comment]
Every word in the title is automatically a search tag. What are some example search tags that would be added to these guides?

**Comment by Zmwang622** [comment]
HS should be a search tag for the high shcool guide
