### ISSUE TITLE
Clean up index.md files

### ISSUE THREAD

**Issue by varughese** [PittCSWiki/pittcswiki#199]
Since the jawns are autogenerated now, we can clean stuff up.

however, some guides should still have bold shit at the top, like

career/index.md should still promote zero to offer like it does, just shouldnt have extra links and stuff

**Comment by varughese** [comment]
also,

move the related things into

"prospective" folder under acacdemics

- high schooler
- cs  v coe

**Comment by Zmwang622** [comment]
can you give me more specifics

**Comment by varughese** [comment]
Step 1, make a prospective folder

1. make a new prospective folder
2. make a new index.md in that folder
index.md should have a title and then add some stuff about "Are you considering CS? Hopefully these guides below help you!"

Move the prospective cs related stuff in there. like right now i think its just high school

**Comment by varughese** [comment]
Step 2

Step 2.
look at every index.md file in src/guides 

delete any references to links (except the 02o one) because we have auto generated jawns now
