### ISSUE TITLE
Add page for general interview preparition tips/tricks

### ISSUE THREAD

**Issue by azharichenko** [PittCSWiki/pittcswiki#20]
Interview
- All about knowing your data structures and practicing 
  - Algorithm handbooks,

- Information firehose, so my best advice is just start. Here's a list of some plans to help out an abundance of links. My advice - just start. And apply to a lot of companies to get practice talking to recruiters and doing interviews. These will make you better

**Comment by varughese** [comment]
some non conventional preparition tips

- https://www.youtube.com/watch?v=QvuQH4_05LI&t=30s

- https://www.amazon.com/Art-Fear-Observations-Rewards-Artmaking/dp/0961454733 
this was also in that popoular how to get a job at a big n talk

A pottery teacher split her class into two halves.
To the first half she said, “You will spend the semester studying pottery, planning, designing, and creating your perfect pot. At the end of the semester, there will be a competition to see whose pot is the best”.
To the other half she said, “You will spend your semester making lots of pots. Your grade will be based on the number of completed pots you finish. At the end of the semester, you’ll also have the opportunity to enter your best pot into a competition.”
The first half of the class threw themselves into their research, planning, and design. Then they set about creating their one, perfect pot for the competition.
The second half of the class immediately grabbed fistfulls of clay and started churning out pots. They made big ones, small ones, simple ones, and intricate ones. Their muscles ached for weeks as they gained the strength needed to throw so many pots.
At the end of class, both halves were invited to enter their most perfect pot into the competition. Once the votes were counted, all of the best pots came from the students that were tasked with quantity. The practice they gained made them significantly better potters than the planners on a quest for a single, perfect pot.

**Comment by Zmwang622** [comment]
Completed initial draft
