### ISSUE TITLE
Add list of project tutorials to guides/skills/projects.

### ISSUE THREAD

**Issue by maxgravitte** [PittCSWiki/pittcswiki#238]
It appears the page, https://pittcs.wiki/skills/projects/ is empty. I am assuming, we are able to write our own guides to building projects, but until then I think we should put links to existing tutorials. Here is a link to a popular GitHub repo with guides to many types of projects: https://github.com/danistefanovic/build-your-own-x

**Comment by Zmwang622** [comment]
I think we're going to write a How to project guide? But that link is good

**Comment by varughese** [comment]
Good idea!
