### ISSUE TITLE
Added sources for where to interact and hangout with all the best people *cough* Pitt CSC PLUG

### ISSUE THREAD

**Issue by azharichenko** [PittCSWiki/pittcswiki#24]
Added sources for where to interact and hangout with all the best people *cough* Pitt CSC PLUG

**Comment by varughese** [comment]
@Zmwang622 write a guide on getting involved with the Pitt community. Obviously should have links to CSC + WiCS stuff, but add what you want

**Comment by varughese** [comment]
@Zmwang622 this would be good one to do next

**Comment by Zmwang622** [comment]
Im tireddddd

**Comment by varughese** [comment]
I can do it?

**Comment by Zmwang622** [comment]
Nah i will
