### ISSUE TITLE
Wrong HyperLink to Blind

### ISSUE THREAD

**Issue by ChuHsin** [PittCSWiki/pittcswiki#257]
At this page 
https://pittcs.wiki/zero-to-offer/mindset/#reddit-blind-linkedin-etc
The hyperlink to blind was set as:
https://pittcs.wiki/zero-to-offer/mindset/www.teamblind.com

**Comment by Zmwang622** [comment]
grossssss

**Comment by tianyizheng02** [comment]
Links are now fixed
