### ISSUE TITLE
Add guides on CS + X (X = other majors) and minors

### ISSUE THREAD

**Issue by varughese** [PittCSWiki/pittcswiki#27]

**Comment by azharichenko** [comment]
Yeah, I think for this issue we just need to slowly include others like Gordon, Hayden, Olivia, etc. for knowledge in economics, fin-ance, etc.

**Comment by varughese** [comment]
For sure. How does it sound that you start with statistics, and I will write a guide on something, and we will try working on the gatsby stuff to make sure its all indexed and formatting nicely and whatever. And then after we got that goin, we can ask them?

**Comment by azharichenko** [comment]
yeah, sounds like a plan. and lol i sort of that of that with issue #58

**Comment by azharichenko** [comment]
I'm currently starting with writing up the minor guide because it's a lot easier and straight forward for me to write

**Comment by azharichenko** [comment]
Hmmm, just realized in relation to issue #23 with making visualizations which in this case are mostly just course graphs. So like I can explain take these stats courses in this order for data science visually. And i think most of these guides would make a lot of use of this.

**Comment by varughese** [comment]
I was thinking that these could MDX https://www.gatsbyjs.org/docs/mdx/

**Comment by azharichenko** [comment]
yeee, i recall this

**Comment by varughese** [comment]
your discord chat lol

**Comment by varughese** [comment]
In my mind, i envisioned a yaml/json file accompanying each markdown file. So something like (this is a rough sketch)

course-guide.md
```md
The core course graph looks like this:
<CourseGraph data="core_course_graph" />
```

course-guide.json
```
{
core_course_graph: [
{from: "CS445", to: "CS1501"},
{from: "CS445", to: "CS447"},
{from: "CS445", to: "CS449"},
{from: "CS4457, to: "CS449", type: "coreq"}
]}
```

and then it would just automagically create

![image](https://user-images.githubusercontent.com/13937711/81365320-c4980980-90b5-11ea-9774-8a00a90242aa.png)

this, and it would be interactive so you could like click nodes on that to take. you to the accompanying course page to get even more info on that course

**Comment by varughese** [comment]
i created that diagram above using dagre-d3 real quick

you can mess around with graphviz here:
https://dagrejs.github.io/project/dagre-d3/latest/demo/interactive-demo.html

```
/* Example */
digraph {
    /* Note: HTML labels do not work in IE, which lacks support for <foreignObject> tags. */
    node [rx=5 ry=5 labelStyle="font: 300 14px 'Helvetica Neue', Helvetica"]
    edge [labelStyle="font: 300 14px 'Helvetica Neue', Helvetica"]

CS1501
CS445
CS447
CS449

CS445 -> CS1501
CS445 -> CS449
CS445 -> CS447
CS447 -> CS449 [label="coreq" style="stroke: #f77; stroke-width: 2px;" arrowheadStyle="fill: #f77"];
}
  ```

**Comment by Zmwang622** [comment]
Turn this issue into one guide that covers a lot of different majors for maintainability sakes.

**Comment by varughese** [comment]
But Alex's stat major guide is pretty long. you don't think  that should be
a separate guide?

**Comment by Zmwang622** [comment]
won't be a major guide, is a minor guide

**Comment by varughese** [comment]
im confused, miscommunication is funny. im going to close this and make a new issue
