### ISSUE TITLE
Broken link detection test fails for links to guide headers

### ISSUE THREAD

**Issue by Richie78321** [PittCSWiki/pittcswiki#337]
A link to a guide header can be made with the following syntax: `[link](#header-name)`. This seems to be a valid usage, as the links work in the preview, but the broken link test is failing.

**Comment by tobias-hildebrandt** [comment]
One solution would be to make `src/utils/sitegraph-generator.js` ignore section links. Then it wouldn't throw any errors when the test is run. However, then some section links could be broken but not caught as an error during testing.

A more robust solution would be to make sure that the linked section (e.g. `#beginner-guides`) actually exists in the markdown file. I don't know much about parsing markdown in JS, but I'm sure there's a library for it. From a quick search, I found https://github.com/remarkjs/remark-validate-links, though I believe that requires the entire `remark` package as a dependency. So a lighter-weight package might be better. Alternatively, we could write our own section-link verifier: something that loads the entire markdown file, searches for section links, then searches the file for a section that corresponds to the link. Off the top of my head, a regex might be useful; the test could even be a shell script using `grep`.

Side note: the entire sitegraph generator file was last touched 2 years ago (see `git blame`) and I think this comment sums it up pretty well: 
https://github.com/PittCSWiki/pittcswiki/blob/2c621c6104720d96f79bc5d2f20921e23c38fb80/src/utils/sitegraph-generator.js#L7
