### ISSUE TITLE
Guide for transfer students / potential transfers

### ISSUE THREAD

**Issue by varughese** [PittCSWiki/pittcswiki#37]
After we publish this wiki there will probs be a lot of CMU students tryna transfer to Pitt

**Comment by Zmwang622** [comment]
@joshs333 Would you be interested in writing this?

**Comment by joshs333** [comment]
Lol @ all the CMU people who will want to transfer to Pitt from CMU after this is published.

When I get time I'll put some words towards this. Will probably do the Robotics one first.

**Comment by Zmwang622** [comment]
Yeah no worries, just wanted you to know there was an opportunity for if
you were interested.
ᐧ

**Comment by katelyn98** [comment]
I would love to contribute! I will work on this after my summer class ends. Thanks for the invitation to collaborate!
