### ISSUE TITLE
Think of a system for easy maintainability in the future

### ISSUE THREAD

**Issue by varughese** [PittCSWiki/pittcswiki#46]
As Jen said, it would be a bad look if this gets outdated in 5 years, so we should have it be suppppppppppppper easy for a new wiki maintainer to come in and fix it up.

This probably means something along the lines of:
- Documenting this repo
- Having CSC be responsible for maintaining the wiki
- Having integrations so that we do not get outdated courses
- Make updating content as easy as editing and updating a markdown file

This needs to be set up organizationally through CSC.

**Comment by Zmwang622** [comment]
I think articles/guides that were not written in the last two years should have a banner at the top saying "This is an outdated article" or something. This way users know what is "outdated" and what's new. Furthermore it incentivizes the leaders in a few years to keep the wiki maintained and up to date.

**Comment by Zmwang622** [comment]
Jenn's main concern with the maintainability of the wiki is that it's going to be outdated in several years and no one will update it. This should help a bit.

**Comment by varughese** [comment]
Added the outdated banner thing. Going to keep this issue open, there should be systematic way that forces CSC officers to apppint someone to manage the wiki. They have to

- Force people to do course reviews
- Review that information, and add it to the sheets
- Check feedback
- Update pages that are going out of date
- Check courses are correct at the beginning of every semester

**Comment by varughese** [comment]
You can close it when u have that system plan out an ingrained into CSC. thanks mr. president @Zmwang622

**Comment by Zmwang622** [comment]
lmaooo sounds good

**Comment by varughese** [comment]
https://docs.google.com/document/d/1QHSqMxn443jM1aPuzK9_ZV3MsiNF66uLTJI4fOzyiok/edit#

**Comment by Zmwang622** [comment]
I think next step is removing the barrier of entry for writing guides. Maybe start doing Google Docs -> Markdown?
