### ISSUE TITLE
Add professor component that links a professor to their rate my professors

### ISSUE THREAD

**Issue by azharichenko** [PittCSWiki/pittcswiki#62]

**Comment by varughese** [comment]
```
azharichenkoToday at 11:46 PM
 `And partially beccause some of these higher level courses are taught by David Stoffer; many students, including myself, find him not to be a very good lecturer and a person to avoid (I really wish this wasn't the case). If you need evidence of this statement view his rate my professor.`

matToday at 11:46 PM

made me think of a new feature
a profressor component
that you can just be like
<Profressor name="David Stroffer>
and it will render his name but also auto link you to his rate my prof
```

**Comment by varughese** [comment]
Also, this would make testimonials better too - each testimonial could just pass the profressor name into the prof component and display a screen

would be sooo cool

**Comment by varughese** [comment]
here is a potential way to do this:

1. scrape rate my professor data into a json file stored in this repo

2. rearchitect how professors are calculated in course testimonials

3. create 'best name matching' algorithm, that can do like tan -> thumrungok to match user input prof names to the rmp names that we have

4. create a professor page that lists all the professors, links them back to the courses they teach
