### ISSUE TITLE
Create a guide for Capstone Courses

### ISSUE THREAD

**Issue by rohit-ganguly** [PittCSWiki/pittcswiki#69]
It would be really helpful to have a guide for all of the capstone courses, Eg: CS 1900, CS 1902, 1950, 1980 , etc. 

Giving a fully in-depth guide for how to do each of them would be fantastic, the only problem is finding people who can help out for the more niche ones (like Research and Co-Op program).

**Comment by varughese** [comment]
fill in 

https://github.com/PittCSWiki/pittcswiki/blob/master/src/pages/guides/capstone.md

**Comment by Zmwang622** [comment]
69? nice
