### ISSUE TITLE
Guide on Computer Science vs Computer Engineering

### ISSUE THREAD

**Issue by varughese** [PittCSWiki/pittcswiki#70]
pat gardner can help out

we should get multiple opinions

- what should incoming frehsmen try to do
- etc

**Comment by rohit-ganguly** [comment]
thank u pat gardner <3

**Comment by varughese** [comment]
Pat wrote this https://docs.google.com/document/d/1glgu9ysGv0w81dR9BM-90wnMoyE3QqIw7WnNeZDOyz8/edit , convert to MD make pr

**Comment by varughese** [comment]
closed by #200
