### ISSUE TITLE
Add guide on trading/quant/wtf is diff between prop and etc

### ISSUE THREAD

**Issue by varughese** [PittCSWiki/pittcswiki#72]
This is waht i know about quant:

- "its called trading bc u trade ur soul for money"
- ming loves jane st

@Zmwang622 where is that link you sent to pat with the cool pdf filled with quant puzzles and all that

**Comment by rohit-ganguly** [comment]
ming and jane street, name a better combo

**Comment by varughese** [comment]
When to Buy and Sell Stock I-III on LeetCode

**Comment by varughese** [comment]
https://docs.google.com/document/d/1Gxjsd59zIqZUhrAu8QErC4s-egwLFcBCWYSYgy6NukY/edit

frranklin sent me this a year ago when wiki was still a brain thought and i asekd for it lol

**Comment by Zmwang622** [comment]
@rohit-ganguly any update?
