### ISSUE TITLE
Add color coding to the course visualizer and graphs

### ISSUE THREAD

**Issue by varughese** [PittCSWiki/pittcswiki#74]
Rohit suggested this and it is a great idea.

Assign each core class a 'color'. Like, 445 red, 449 yellow, 1501 orange, etc. In the course visualization, color code each one to show what the prereqs are.

We can carry this over to the course graphs as well. 

Maybe one way to do this is to have CSS classes like .course-pill-cs0445 { background-color: red; }, and anything that deals with courses can add that id.

We also can create a legend component too as apart of this if we want.

**Comment by varughese** [comment]
Should we parse the prereqs using the prereq parser? Or manually write them

Pro:
Would auto update. Less manual. Connected to Pitt

Con:
Requires parser to be really good and resistant to bugs. Some requisites are so bad that they need manually intervention anyways

**Comment by rohit-ganguly** [comment]
We can just update as necessary over the years I think - SCI academic requirements won't be changing for long.

**Comment by varughese** [comment]
Tru tru. Wiki 3.0 we can automate it and do it for every major
