### ISSUE TITLE
figure out how to replace CMP 401 into CS 401 in a resuable / maintainble way

### ISSUE THREAD

**Issue by varughese** [PittCSWiki/pittcswiki#87]
need like some config to write down if classes get replaced, can auto add redirects and stuff like that

**Comment by Zmwang622** [comment]
Wouldn't Dr. L's data help for this

**Comment by varughese** [comment]
No, we need in a way in our system to represent that CS 401 == CMP 401, whereas getting the new peoplesoft data would just give us information about CMP 401. fixing this in #98
