### ISSUE TITLE
Adding guide for scheduling courses, with tips from current students

### ISSUE THREAD

**Issue by azharichenko** [PittCSWiki/pittcswiki#9]

**Comment by varughese** [comment]
file is in src/pages/guides/scheduling.mdx

**Comment by varughese** [comment]
who tryna do this, file is in src/guides/academics/scheduling.mdx

**Comment by varughese** [comment]
1. 1501 writing?
2. is x too hard to take with x
3. APs

a lot of stuff to cover

**Comment by varughese** [comment]
@glu99331 would you be open to writing this? we can collab on it together in a google doc

**Comment by glu99331** [comment]
Yeah, I'd be fine with writing this

**Comment by varughese** [comment]
Thanks gordon! the current page is : https://pittcswiki.netlify.app/academics/scheduling

right now theres a graph you can click on, but we should work on adding more words below that and answer commonly asked questions. you can add me to the google doc you write it in and we can work on it together

**Comment by Zmwang622** [comment]
@glu99331 Can you get this by the 14th?

**Comment by varughese** [comment]
We can all colab on it
