### ISSUE TITLE
Sort Testimonial by date, professor name, rating

### ISSUE THREAD

**Issue by Zmwang622** [PittCSWiki/pittcswiki#91]
There are a lot of reviews now and it might be hard for users to get the reviews they want. Having a sorting feature can help them find specific professors, the most recent reviews, etc.

**Comment by varughese** [comment]
if you want to take a class you, wouldnt you just want to see the most recent reviews. which is what it sorts on my default

**Comment by Zmwang622** [comment]
Ig, but what if they wanted to see Garrison vs Farnan for 1501? idk

**Comment by varughese** [comment]
Tru tru. Think that's more rate my profressor though. Maybe we can add a
profressors that teach this section with links to their RMP? Plus once we
get more data we can add average difficulty and stuff like that

**Comment by varughese** [comment]
once we average > 10 testimonials a page lets come back to this

**Comment by Zmwang622** [comment]
agreed. I think we should also look into having a Professor page. Ik we're not RMP but RMP's functionality isn't amazing to beginning with? idk idk

**Comment by varughese** [comment]
what do you think they do not do well that we can do better? i think having a profressor page would just be duplicating RMP 

wdyt @azharichenko
