### ISSUE TITLE
Resume Upload System for Pitt Students

### ISSUE THREAD

**Issue by Zmwang622** [PittCSWiki/pittcswiki#95]
Putting this here because I'm removing it from the Resume.md file

Also since we may be expecting traffic from non pitt students we will have to figure out a way to only get resumes from pitt students

**Comment by varughese** [comment]
email to pittcsc+resume@gmail.com and have a filter on that email?

or a google form where they upload

**Comment by varughese** [comment]
is that enough do you think? @Zmwang622

**Comment by Zmwang622** [comment]
I think both are good ideas. Maybe have a submission page or something that does email validation before they send emails so our spam won't get full?

**Comment by varughese** [comment]
Or just have a google form, where they can upload it and then email csc
when that happens

It could be a potential pitt prject to create a resume review platform

**Comment by Zmwang622** [comment]
yes i like that idea

**Comment by Zmwang622** [comment]
This shouldn't be closed. I haven't made a form yet

**Comment by varughese** [comment]
oops

**Comment by Zmwang622** [comment]
@varughese Did you look the form over

**Comment by varughese** [comment]
@Zmwang622 looks good, add link to the resume guide and then close issue

**Comment by Zmwang622** [comment]
Added link, it doesn't appear on the edit mode but if you visit the share link it's a link
